### ISSUE TITLE
i dont know :(

### ISSUE THREAD

**Issue by nikolaibarbravas** [mariosemes/PornHub-downloader-python#22] opened 2020-06-17 18:33 UTC
File "phdler.py", line 55, in <module>
    main()
  File "phdler.py", line 21, in main
    add_check(sys.argv[2])
  File "F:\PORN\PornHub-downloader-python-master\functions.py", line 88, in add_check
    add_item(name_check)
  File "F:\PORN\PornHub-downloader-python-master\functions.py", line 273, in add_item
    item_name = get_item_name(item_type, name_check)
  File "F:\PORN\PornHub-downloader-python-master\functions.py", line 105, in get_item_name
    title = finder.find(class_='title').text.replace('\n', '').strip()
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by cardoso-neto** [comment] 2020-09-03 04:13
A quick and dirty fix: comment out line 94 of functions.py.
This is what it should look like:
```python
91 def get_item_name(item_type, url_item):
92     url = url_item
93     html = request.urlopen(url).read().decode('utf8')
94     # html = html[:60]
95
96     soup = BeautifulSoup(html, 'html.parser')
```
Duplicate of #18

**Comment by mariosemes** [comment] 2021-03-25 21:04
The development of this tools is deprecated.
Feel free to fork it and keep on developing it.

**Closed by mariosemes** 2021-03-25 21:04 UTC
